version: '3'

services:
  database:
    image: postgres:13
    environment:
      POSTGRES_DB: legacy_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 20221428H
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d legacy_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - internal-network

  legacy-app:
    build:
      context: ./legacy-app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      database:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://admin:20221428H@database:5432/legacy_db
    networks:
      - internal-network

  new-microservice:
    build:
      context: ./new-microservice
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    depends_on:
      database:
        condition: service_healthy
    environment:
      - LEGACY_APP_URL=http://legacy-app:8000
    networks:
      - internal-network

volumes:
  postgres_data:

networks:
  internal-network:
    driver: bridge
    internal: true