apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_USER: YWRtaW4= #admin en base64
  POSTGRES_PASSWORD: MjAyMjE0MjhI #20221428H en base64
  POSTGRES_DB: bGVnYWN5LWRi #legacy-db en base64